name: barcode_app
description: A barcode scanning app with AI backend.
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera:
  http:
  path_provider:
  share_plus:
  image:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

